version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=myrecipedb
    ports:
      - 5432:5432
    restart: always
  api:
    build: .
    container_name: myrecipeapp
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://postgres:5432/myrecipedb
      db-username: postgres
      db-password: mysecretpassword
    depends_on:
      - postgres